spring cleaning and first hop
NybyDK/MPLS-Simulation pull request #103
Opened 2024-04-03 09:13 UTC by TSKsmiley

2024-04-03 09:41 UTC, NybyDK commented
I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it https://github.com/sherlock-project/sherlock#installation
 
WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. these dumbfucks think that everyone is a developer and understands code. well i am not and i don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me. STUPID FUCKING SMELLY NERDS 🤓

2024-04-03 12:05 UTC, NybyDK requested changes
anti merge, we need #108

2024-04-03 12:28 UTC, JakobTopholt requested changes
I generally speaking can approve it with our without my addition, but I'd like my addition

2024-04-03 12:28 UTC, JakobTopholt commented on src/lib/components/Packet.svelte
> +    fill: #6495ed;
```suggestion
    fill: #6495ed; /*light blue*/
```

2024-04-03 12:30 UTC, JakobTopholt approved these changes

2024-04-03 16:46 UTC, NybyDK approved these changes

2024-04-04 06:29 UTC, JakobTopholt approved these changes

2024-04-04 06:29 UTC, merged