41 use icons for nodes
NybyDK/MPLS-Simulation pull request #156
Opened 2024-04-22 07:35 UTC by JakobTopholt

Ignore my sanity fading with the commits.

Imo the colors are ok, but we didn't really talk about this/argue.

2024-04-22 07:42 UTC, TSKsmiley requested changes

2024-04-22 07:42 UTC, TSKsmiley commented on src/lib/components/Router.svelte
> +    href={`/${router.type}Router.svg`}
this should be a RouterSVG.svelte file
aka look at this for reference: https://svelte.dev/repl/86553af5c35449ab88e34f1e50eb298f?version=3.38.0

2024-04-22 07:42 UTC, TSKsmiley commented on src/lib/components/Router.svelte
> +    href={`/${router.type}Router.svg`}
and don't use image tag

2024-05-06 09:31 UTC, NybyDK approved these changes

2024-05-06 09:31 UTC, TSKsmiley approved these changes

2024-05-06 09:32 UTC, merged