Naive experimental way of trying to move packets (overall BAD)
NybyDK/MPLS-Simulation pull request #75
Opened 2024-03-21 09:18 UTC by NybyDK

2024-03-21 09:24 UTC, NybyDK commented
I will not merge until @TSKsmiley has reviewed, as he knows the most about TypeScript and the overall structure needs to be good
But @JakobTopholt and @Stormlighter feel free to review as well

2024-03-21 10:14 UTC, TSKsmiley requested changes

2024-03-21 10:14 UTC, TSKsmiley commented on src/lib/classes/MPLS/LER.ts
> +      );
we might want to map the routers by address and have a map per type

2024-03-21 10:14 UTC, TSKsmiley commented on src/lib/classes/MPLS/Packet.ts
> +    this.nextHop = paths.getPath(source.id, destination.id)?.[1] as Router;
i think we can use a type guard here as to not use as

2024-03-21 10:14 UTC, TSKsmiley commented on src/lib/classes/NetworkStore.ts
> +  private _packets: Packet[] = [];
map the packets

2024-03-21 10:43 UTC, TSKsmiley approved these changes

2024-03-21 10:54 UTC, Stormlighter submitted a review, later dismissed

2024-03-22 07:40 UTC, TSKsmiley approved these changes

2024-03-22 07:40 UTC, merged